# see https://github.com/ZeroCM/zcm/blob/master/.travis.yml
language: cpp

os:
- linux


dist: xenial

before_install:
  - sudo apt-get install -y uuid-dev libsystemd-dev liblz4-dev libcurl4-nss-dev libzmq-dev libczmq-dev

script: ./waf configure build 
